### ISSUE TITLE
init命令报错

### ISSUE THREAD

**Issue by iamwelk** [easy-mock/easy-mock-cli#1]
### 报错信息
![image](https://user-images.githubusercontent.com/6983075/30906270-f4557ff0-a3a9-11e7-9c9c-c84c3c5df409.png)

### 配置
![image](https://user-images.githubusercontent.com/6983075/30906306-0de1f82c-a3aa-11e7-8717-9491efcccb45.png)

**Comment by chuangker** [comment]
我试了一下，没问题呀。

**Comment by wuzhishuo** [comment]
project id 前面多了个空格

**Comment by iamwelk** [comment]
多谢两位~
